# docker yaml inheritence thing
# environment:
#    MYSQL_URL: 'drug_inventory'
#    MYSQL_USER: 'user'
#    MYSQL_PASSWORD: 'password'

services:
  app:
    build:
      context: ionic
      dockerfile: ./Dockerfile
    container_name: ionic-web
    ports:
      - 4200:4200
    expose:
      - 4200 # localhost:4200
    volumes:
      - ~/projects/piql/ionic:/project
    command: ionic serve --port=4200 --host=0.0.0.0
  backend:
    image: python:3.12-slim
    container_name: python_backend
    environment:
      MYSQL_URL: 'drug_inventory'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - 4201:4201
    expose:
      - 4201 # api calls from the frontend will go to python_backend:4201
    volumes:
      - ~/projects/piql/python:/piql
    command: tail -f /dev/null
  database:
    image: arm64v8/mysql
    container_name: drug_inventory
    environment:
      MYSQL_DATABASE: 'drugs'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306 # may not need to expose this.
    volumes:
      - ./data/database/data:/var/lib/mysql
      - "./data/database/scripts/creation.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./data/database/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
